# Generated by Django 5.1.1 on 2024-11-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_wardrobe_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='feet',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='head',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='lower',
        ),
        migrations.RemoveField(
            model_name='fit',
            name='upper',
        ),
    ]
